CREATE TABLE IF NOT EXISTS quote_issuers (
  id SERIAL PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

ALTER TABLE quotes ADD COLUMN IF NOT EXISTS issuer_id INTEGER REFERENCES quote_issuers(id) ON DELETE SET NULL;
